version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - symfony

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - symfony

    db:
        image: postgres:15
        container_name: symfony_db
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        networks:
            - symfony

networks:
    symfony:
